"""initial schema

Revision ID: 2b324fcb3ab6
Revises: 
Create Date: 2026-05-12 07:10:10.318580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b324fcb3ab6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'active', 'completed', name='exercise_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ttps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mitre_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tactic', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('platform', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ttps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ttps_mitre_id'), ['mitre_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_ttps_tactic'), ['tactic'], unique=False)

    op.create_table('exercise_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('ttp_id', sa.Integer(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tool_used', sa.String(length=200), nullable=True),
    sa.Column('command_used', sa.Text(), nullable=True),
    sa.Column('red_notes', sa.Text(), nullable=True),
    sa.Column('detected', sa.Boolean(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detection_method', sa.String(length=200), nullable=True),
    sa.Column('alert_name', sa.String(length=200), nullable=True),
    sa.Column('response_action', sa.Text(), nullable=True),
    sa.Column('blue_notes', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Enum('detected', 'missed', 'partial', name='outcome_enum'), nullable=True),
    sa.Column('gap_identified', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ttp_id'], ['ttps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercise_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_entries_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_entries_ttp_id'), ['ttp_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_entries_ttp_id'))
        batch_op.drop_index(batch_op.f('ix_exercise_entries_exercise_id'))

    op.drop_table('exercise_entries')
    with op.batch_alter_table('ttps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ttps_tactic'))
        batch_op.drop_index(batch_op.f('ix_ttps_mitre_id'))

    op.drop_table('ttps')
    op.drop_table('exercises')
    # ### end Alembic commands ###
