"""add source and destination to exercise_entries

Revision ID: cb13d14ba387
Revises: 2b324fcb3ab6
Create Date: 2026-05-12 11:01:40.072805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb13d14ba387'
down_revision = '2b324fcb3ab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('destination', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_entries', schema=None) as batch_op:
        batch_op.drop_column('destination')
        batch_op.drop_column('source')

    # ### end Alembic commands ###
